name: Train and Validate

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Preprocess data
        run: python preprocess.py

      - name: Train model
        run: python train.py

      - name: Validate model
        run: python model_validation.py